local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>ff', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.live_grep, {})
vim.keymap.set('n', '<leader>fb', builtin.buffers, {})
vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
vim.keymap.set('n', '<leader>far', builtin.lsp_references, {})
vim.keymap.set('v', '<leader>far', builtin.lsp_references, {})
vim.keymap.set('n', '<leader>icc', builtin.lsp_incoming_calls, {})
vim.keymap.set('n', '<leader>ogc', builtin.lsp_outgoing_calls, {})
vim.keymap.set('n', '<leader>giw', ':Vimgrep <c-r>=expand("<cword>")<cr><cr>', {})
vim.keymap.set('n', '<c-p>', builtin.git_files, {})
